image: zenhaskell/foundation:latest

before_script:
- cachix use locallycompact
- export LC_ALL="en_US.utf8"
- |
  if [ -z ${CACHIX_CONFIG} ]; then
    echo "$CACHIX_CONFIG" > /root/.cachix.dhall
  fi

pages:
  stage: deploy
  script:
  - |
    nix-shell
    if [ -z ${CACHIX_USER} ]; then
      for x in $buildInputs; do
        nix-store -qR --include-outputs "$PUSH" $(nix-store -q --deriver "$PUSH") | cachix push "$CACHIX_USER" -c /root/.cachix.dhall
      done
    fi
  - nix-shell --command 'shake'
  - nix-shell --command 'shake pdf'
  - nix-shell --command 'shake beamer'
  artifacts:
    paths:
    - public
