image: zenhaskell/foundation:latest

before_script:
- cachix use locallycompact

pages:
  stage: deploy
  script:
  - nix-shell
  - |
    if [ -z "${CACHIX_USER}" && -z "${CACHIX_SIGNING_KEY}" ]; then
      nix-shell
      for x in $buildInputs; do
        nix-store -qR --include-outputs "$x" $(nix-store -q --deriver "$x") | cachix push "$CACHIX_USER"
      done
    fi
  - nix-shell --command 'shake'
  - nix-shell --command 'shake pdf'
  - nix-shell --command 'shake beamer'
  artifacts:
    paths:
    - public
