image: zenhaskell/analysis:lts-12.21

pages:
  stage: deploy
  script:
  - stack build
  - stack exec -- site
  - stack exec -- site pdf
  - stack exec -- site beamer
  artifacts:
    paths:
    - public
